language: erlang
otp_release:
  - 20.0
sudo: false
install:
  - make
  - dialyzer --build_plt --apps erts kernel stdlib crypto mnesia sasl common_test inets ssl
script:
  - make tests
  - make dialyze
